---
- hosts: dss
  become: yes
  vars:
    dss_version: "7.0.1"
  tasks:
  - name: Create datadir
    file:
      path: /dss/data
      state: directory
      owner: dssuser
      group: dssuser
      mode: 0711

  - name: Create installdir
    file:
      path: /dss/install
      state: directory
      owner: dssuser
      group: dssuser
      mode: 0711

  - name: Download DSS 
    get_url: 
      url: https://downloads.dataiku.com/public/studio/{{dss_version}}/dataiku-dss-{{dss_version}}.tar.gz
      dest: /dss/install/dataiku.tar.gz
      mode: '0440'

  - name: Get Hadoop Lib  
    get_url:  
      url: https://downloads.dataiku.com/public/studio/{{dss_version}}/dataiku-dss-hadoop3-standalone-libs-generic-{{dss_version}}.tar.gz
      dest: /dss/install/dataiku-hadoop3.tar.gz
      mode: '0440'

  - name: Get Spark Lib  
    get_url:    
      url: https://downloads.dataiku.com/public/studio/{{dss_version}}/dataiku-dss-spark-standalone-{{dss_version}}-2.4.3-generic-hadoop3.tar.gz
      dest: /dss/install/dataiku-spark.tar.gz
      mode: '0440'
  
  - name: Open tarball
    unarchive: 
      src: /dss/install/dataiku.tar.gz
      dest: /dss/install/
      remote_src: yes

  - name: install pexpect
    yum:
      name: python3-pexpect
      state: present
  
  - name: install-deps
    expect: 
      command: /dss/install/dataiku-dss-{{dss_version}}/scripts/install/install-deps.sh
      responses:
        .*\nIs this ok \[y\/N\]: y 
      timeout: 600
    
  - name: install DSS 
    become: yes
    become_user: dssuser
    shell: /dss/install/dataiku-dss-{{dss_version}}/installer.sh -d /dss/data -p 11000
  
  - name: start DSS
    become: yes
    become_user: dssuser
    command: /dss/data/bin/dss start
    
  # - name: run-on-boot
...