---
- hosts: dss
  become: yes                             
  vars:
    dss_disk: /dev/xvdb
  tasks:
  - name: Format the attached disk        
    filesystem:
      fstype: ext4
      dev: "{{dss_disk}}"
      resizefs: yes

  - name: Get UUID
    shell: >
      blkid | grep xvdb |
      sed -n 's/.*UUID=\"\([^\"]*\)\".*/\1/p'
    register: uuid

  - name: Create DSS directory
    file:
      path: /dss
      owner: dssuser
      group: dssuser
      mode: 0711
      state: directory
      
  - name: Mount disk
    mount:
      backup: yes
      path: /dss
      src: "UUID={{uuid.stdout}}"
      fstype: ext4
      boot: yes
      state: present

...