
---
# create user and group for dssuser
- hosts: dss
  become: yes                             # become root (to install packages)
  tasks:
    - name: Create group for dssuser
      group: 
        name: dss
        state: present
    - name: Create dssuser
      user:
        name: dssuser
        groups: dss, wheel
        createhome: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Get the public key for dssuser
      fetch:
        src: /home/dssuser/.ssh/id_rsa.pub
        dest: ~/.ssh/
        flat: yes
...

